### ISSUE TITLE
TODO left

### ISSUE THREAD

**Issue by paulinegarelli** [Kawbat/dd2480-jabref#76]
For P:

- [ ] The onboarding experience of the group is briefly documented.
- [ ] The contribution of each group member is documented. The work carried out is commensurate with
the expected time spent (20–25 hours per person).
- [ ] At least some issues are non-trivial in the sense that they do not all affect only single, local functions,
but at least multiple functions, units, classes, files, or modules.
- [ ] Requirements related to the functionality are identified and described in a systematic way. Each
requirement has a name (ID), title, and description. The description can be one paragraph per requirement.
- [ ] Changes to the code and test suite are shown and documented, e.g., as a patch.
- [ ] Tests are automated, their outcome is documented, e.g., as a test log.
- [ ] Key features affected by the issue are shown in UML class diagrams (for refactorings: include before/after).
- [ ] The overall work carried out, and experience gained, are documented. In particular, mention your experience about the given documentation/examples of the project, its tool framework, and the interaction
within your team (using the Essence framework) and with the community of the project.

For P+ (at least 4/7):

- [ ] The architecture and purpose of the system are presented in an overview of about 1–1.5 pages; consider
using a diagram. Note: If you manage to improve on existing documentation or fill a gap in the project
here, please consider making your documentation available to the project; they may be grateful for it!
- [ ]  Updates in the source are put into context with the overall software architecture and discussed, relating
them to design patterns and/or refactoring patterns.
- [ ] Relevant test cases (existing tests and updated/new tests related to the refactored code) are traced to
requirements.
- [ ] Your patch is clean in that it (a) removes but does not comment out obsolete code and (b) does not
produce extraneous output that is not required for your task (such as debug output) and (c) does not
add unnecessary whitespace changes (such as adding or removing empty lines).
- [ ] Patches are accepted by the project, or considered for acceptance. (This requires a link to an accepted
commit, or a discussion item.) Note: the patch must be submitted by the assignment deadline, but it
may be accepted later. (Please notify us if this extra point is necessary for a P+.)
- [ ] You can argue critically about the benefits, drawbacks, and limitations of your work carried out, in
the context of current software engineering practice, such as the SEMAT kernel (covering alphas other
than Team/Way of Working).
- [ ]  You have done something extraordinary that exceeds the scope of the assignment, and which you can
be proud of.
